image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
    - build
    - test
    - deploy

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json"

build_dev:
    stage: build
    only: 
      - develop
    script:
      - dotnet nuget add source $PACKAGE_REGISTRY_URL --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
      - dotnet restore
      - dotnet pack -c Release -o nuget --version-suffix "dev"
    tags:
      - docker
    artifacts:
        paths:
          - nuget/

build:
    stage: build
    only: 
      - docker-labs
    script:
      - dotnet nuget add source $PACKAGE_REGISTRY_URL --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
      - dotnet restore
      - dotnet pack -c Release -o nuget --version-suffix "20230421"
    tags:
      - docker
    artifacts:
        paths:
          - nuget/          

test:
    stage: test
    only: 
      - develop
      - docker-labs
    tags:
      - docker
    script:
      - echo "Tests are not implemented yet"

sonar:
    variables:
      SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
      GIT_DEPTH: "0"
    cache:
      key: "${CI_JOB_NAME}"
      paths:
        - .sonar/cache
    stage: test
    only:
      - merge_requests
    tags:
      - docker
    script: 
      - "apt-get update"
      - "apt-get install --yes openjdk-11-jre"
      - "dotnet tool install --global dotnet-sonarscanner"
      - "export PATH=\"$PATH:$HOME/.dotnet/tools\""
      - dotnet nuget add source https://nuget.devexpress.com/api -n DXFeed -u DevExpress -p $DX_NUGET_TOKEN --store-password-in-clear-text
      - "dotnet sonarscanner begin /k:\"$SONAR_KEY\" /d:sonar.login=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_URL\" "
      - "dotnet build"
      - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
    allow_failure: true

deploy:
    stage: deploy
    only: 
      - develop
      - docker-labs
    tags:
      - docker
    script:
      - dotnet nuget add source $PACKAGE_REGISTRY_URL --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
      - dotnet nuget push "nuget/*.nupkg" --source gitlab
