image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
    - build
    - test
    - deploy

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json"

build:
    stage: build
    only: 
      - develop
    script:
      - dotnet nuget add source https://nuget.devexpress.com/api -n DXFeed -u DevExpress -p $DX_NUGET_TOKEN --store-password-in-clear-text
      - dotnet restore
      - dotnet pack -c Release -o nuget --version-suffix "$(date +%Y%m%d)"
    tags:
      - docker
    artifacts:
        paths:
          - nuget/

test:
    stage: test
    only: 
      - develop
    tags:
      - docker
    script:
      - echo "Tests are not implemented yet"

deploy:
    stage: deploy
    only: 
      - develop
    tags:
      - docker
    script:
      - dotnet nuget add source $PACKAGE_REGISTRY_URL --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
      - dotnet nuget push "nuget/*.nupkg" --source gitlab
