### YamlMime:ManagedReference
items:
- uid: Siesa.SDK.Frontend.Application.IViewdefManager
  commentId: T:Siesa.SDK.Frontend.Application.IViewdefManager
  id: IViewdefManager
  parent: Siesa.SDK.Frontend.Application
  children:
  - Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  langs:
  - csharp
  - vb
  name: IViewdefManager
  nameWithType: IViewdefManager
  fullName: Siesa.SDK.Frontend.Application.IViewdefManager
  type: Interface
  source:
    remote:
      path: Siesa.SDK.Frontend/Application/ViewdefManager.cs
      branch: docFX
      repo: https://gitlab.siesadev.com/conversion/sdk/sdk.git
    id: IViewdefManager
    path: ../Siesa.SDK.Frontend/Application/ViewdefManager.cs
    startLine: 14
  assemblies:
  - Siesa.SDK.Frontend
  namespace: Siesa.SDK.Frontend.Application
  syntax:
    content: public interface IViewdefManager
    content.vb: Public Interface IViewdefManager
- uid: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  commentId: M:Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  id: GetViewdef(System.String,System.String)
  parent: Siesa.SDK.Frontend.Application.IViewdefManager
  langs:
  - csharp
  - vb
  name: GetViewdef(string, string)
  nameWithType: IViewdefManager.GetViewdef(string, string)
  fullName: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(string, string)
  type: Method
  source:
    remote:
      path: Siesa.SDK.Frontend/Application/ViewdefManager.cs
      branch: docFX
      repo: https://gitlab.siesadev.com/conversion/sdk/sdk.git
    id: GetViewdef
    path: ../Siesa.SDK.Frontend/Application/ViewdefManager.cs
    startLine: 15
  assemblies:
  - Siesa.SDK.Frontend
  namespace: Siesa.SDK.Frontend.Application
  syntax:
    content: string GetViewdef(string businessName, string viewName)
    parameters:
    - id: businessName
      type: System.String
    - id: viewName
      type: System.String
    return:
      type: System.String
    content.vb: Function GetViewdef(businessName As String, viewName As String) As String
  overload: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef*
  nameWithType.vb: IViewdefManager.GetViewdef(String, String)
  fullName.vb: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(String, String)
  name.vb: GetViewdef(String, String)
references:
- uid: Siesa.SDK.Frontend.Application
  commentId: N:Siesa.SDK.Frontend.Application
  href: Siesa.html
  name: Siesa.SDK.Frontend.Application
  nameWithType: Siesa.SDK.Frontend.Application
  fullName: Siesa.SDK.Frontend.Application
  spec.csharp:
  - uid: Siesa
    name: Siesa
    href: Siesa.html
  - name: .
  - uid: Siesa.SDK
    name: SDK
    href: Siesa.SDK.html
  - name: .
  - uid: Siesa.SDK.Frontend
    name: Frontend
    href: Siesa.SDK.Frontend.html
  - name: .
  - uid: Siesa.SDK.Frontend.Application
    name: Application
    href: Siesa.SDK.Frontend.Application.html
  spec.vb:
  - uid: Siesa
    name: Siesa
    href: Siesa.html
  - name: .
  - uid: Siesa.SDK
    name: SDK
    href: Siesa.SDK.html
  - name: .
  - uid: Siesa.SDK.Frontend
    name: Frontend
    href: Siesa.SDK.Frontend.html
  - name: .
  - uid: Siesa.SDK.Frontend.Application
    name: Application
    href: Siesa.SDK.Frontend.Application.html
- uid: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef*
  commentId: Overload:Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef
  href: Siesa.SDK.Frontend.Application.IViewdefManager.html#Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  name: GetViewdef
  nameWithType: IViewdefManager.GetViewdef
  fullName: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
