### YamlMime:ManagedReference
items:
- uid: Siesa.SDK.Frontend.Application.ViewdefManager
  commentId: T:Siesa.SDK.Frontend.Application.ViewdefManager
  id: ViewdefManager
  parent: Siesa.SDK.Frontend.Application
  children:
  - Siesa.SDK.Frontend.Application.ViewdefManager.#ctor(Microsoft.Extensions.Configuration.IConfiguration)
  - Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef(System.String,System.String)
  langs:
  - csharp
  - vb
  name: ViewdefManager
  nameWithType: ViewdefManager
  fullName: Siesa.SDK.Frontend.Application.ViewdefManager
  type: Class
  source:
    remote:
      path: Siesa.SDK.Frontend/Application/ViewdefManager.cs
      branch: docFX
      repo: https://gitlab.siesadev.com/conversion/sdk/sdk.git
    id: ViewdefManager
    path: ../Siesa.SDK.Frontend/Application/ViewdefManager.cs
    startLine: 17
  assemblies:
  - Siesa.SDK.Frontend
  namespace: Siesa.SDK.Frontend.Application
  syntax:
    content: 'public class ViewdefManager : IViewdefManager'
    content.vb: Public Class ViewdefManager Implements IViewdefManager
  inheritance:
  - System.Object
  implements:
  - Siesa.SDK.Frontend.Application.IViewdefManager
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Siesa.SDK.Frontend.Application.ViewdefManager.#ctor(Microsoft.Extensions.Configuration.IConfiguration)
  commentId: M:Siesa.SDK.Frontend.Application.ViewdefManager.#ctor(Microsoft.Extensions.Configuration.IConfiguration)
  id: '#ctor(Microsoft.Extensions.Configuration.IConfiguration)'
  parent: Siesa.SDK.Frontend.Application.ViewdefManager
  langs:
  - csharp
  - vb
  name: ViewdefManager(IConfiguration)
  nameWithType: ViewdefManager.ViewdefManager(IConfiguration)
  fullName: Siesa.SDK.Frontend.Application.ViewdefManager.ViewdefManager(Microsoft.Extensions.Configuration.IConfiguration)
  type: Constructor
  source:
    remote:
      path: Siesa.SDK.Frontend/Application/ViewdefManager.cs
      branch: docFX
      repo: https://gitlab.siesadev.com/conversion/sdk/sdk.git
    id: .ctor
    path: ../Siesa.SDK.Frontend/Application/ViewdefManager.cs
    startLine: 20
  assemblies:
  - Siesa.SDK.Frontend
  namespace: Siesa.SDK.Frontend.Application
  syntax:
    content: public ViewdefManager(IConfiguration configuration)
    parameters:
    - id: configuration
      type: Microsoft.Extensions.Configuration.IConfiguration
    content.vb: Public Sub New(configuration As IConfiguration)
  overload: Siesa.SDK.Frontend.Application.ViewdefManager.#ctor*
  nameWithType.vb: ViewdefManager.New(IConfiguration)
  fullName.vb: Siesa.SDK.Frontend.Application.ViewdefManager.New(Microsoft.Extensions.Configuration.IConfiguration)
  name.vb: New(IConfiguration)
- uid: Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef(System.String,System.String)
  commentId: M:Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef(System.String,System.String)
  id: GetViewdef(System.String,System.String)
  parent: Siesa.SDK.Frontend.Application.ViewdefManager
  langs:
  - csharp
  - vb
  name: GetViewdef(string, string)
  nameWithType: ViewdefManager.GetViewdef(string, string)
  fullName: Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef(string, string)
  type: Method
  source:
    remote:
      path: Siesa.SDK.Frontend/Application/ViewdefManager.cs
      branch: docFX
      repo: https://gitlab.siesadev.com/conversion/sdk/sdk.git
    id: GetViewdef
    path: ../Siesa.SDK.Frontend/Application/ViewdefManager.cs
    startLine: 38
  assemblies:
  - Siesa.SDK.Frontend
  namespace: Siesa.SDK.Frontend.Application
  example: []
  syntax:
    content: public string GetViewdef(string businessName, string viewName)
    parameters:
    - id: businessName
      type: System.String
    - id: viewName
      type: System.String
    return:
      type: System.String
    content.vb: Public Function GetViewdef(businessName As String, viewName As String) As String
  overload: Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef*
  implements:
  - Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  nameWithType.vb: ViewdefManager.GetViewdef(String, String)
  fullName.vb: Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef(String, String)
  name.vb: GetViewdef(String, String)
references:
- uid: Siesa.SDK.Frontend.Application
  commentId: N:Siesa.SDK.Frontend.Application
  href: Siesa.html
  name: Siesa.SDK.Frontend.Application
  nameWithType: Siesa.SDK.Frontend.Application
  fullName: Siesa.SDK.Frontend.Application
  spec.csharp:
  - uid: Siesa
    name: Siesa
    href: Siesa.html
  - name: .
  - uid: Siesa.SDK
    name: SDK
    href: Siesa.SDK.html
  - name: .
  - uid: Siesa.SDK.Frontend
    name: Frontend
    href: Siesa.SDK.Frontend.html
  - name: .
  - uid: Siesa.SDK.Frontend.Application
    name: Application
    href: Siesa.SDK.Frontend.Application.html
  spec.vb:
  - uid: Siesa
    name: Siesa
    href: Siesa.html
  - name: .
  - uid: Siesa.SDK
    name: SDK
    href: Siesa.SDK.html
  - name: .
  - uid: Siesa.SDK.Frontend
    name: Frontend
    href: Siesa.SDK.Frontend.html
  - name: .
  - uid: Siesa.SDK.Frontend.Application
    name: Application
    href: Siesa.SDK.Frontend.Application.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Siesa.SDK.Frontend.Application.IViewdefManager
  commentId: T:Siesa.SDK.Frontend.Application.IViewdefManager
  parent: Siesa.SDK.Frontend.Application
  href: Siesa.SDK.Frontend.Application.IViewdefManager.html
  name: IViewdefManager
  nameWithType: IViewdefManager
  fullName: Siesa.SDK.Frontend.Application.IViewdefManager
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Siesa.SDK.Frontend.Application.ViewdefManager.#ctor*
  commentId: Overload:Siesa.SDK.Frontend.Application.ViewdefManager.#ctor
  href: Siesa.SDK.Frontend.Application.ViewdefManager.html#Siesa.SDK.Frontend.Application.ViewdefManager.#ctor(Microsoft.Extensions.Configuration.IConfiguration)
  name: ViewdefManager
  nameWithType: ViewdefManager.ViewdefManager
  fullName: Siesa.SDK.Frontend.Application.ViewdefManager.ViewdefManager
  nameWithType.vb: ViewdefManager.New
  fullName.vb: Siesa.SDK.Frontend.Application.ViewdefManager.New
  name.vb: New
- uid: Microsoft.Extensions.Configuration.IConfiguration
  commentId: T:Microsoft.Extensions.Configuration.IConfiguration
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.configuration.iconfiguration
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Extensions.Configuration.IConfiguration
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.configuration
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.configuration
- uid: Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef*
  commentId: Overload:Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef
  href: Siesa.SDK.Frontend.Application.ViewdefManager.html#Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef(System.String,System.String)
  name: GetViewdef
  nameWithType: ViewdefManager.GetViewdef
  fullName: Siesa.SDK.Frontend.Application.ViewdefManager.GetViewdef
- uid: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  commentId: M:Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  parent: Siesa.SDK.Frontend.Application.IViewdefManager
  isExternal: true
  href: Siesa.SDK.Frontend.Application.IViewdefManager.html#Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  name: GetViewdef(string, string)
  nameWithType: IViewdefManager.GetViewdef(string, string)
  fullName: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(string, string)
  nameWithType.vb: IViewdefManager.GetViewdef(String, String)
  fullName.vb: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(String, String)
  name.vb: GetViewdef(String, String)
  spec.csharp:
  - uid: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
    name: GetViewdef
    href: Siesa.SDK.Frontend.Application.IViewdefManager.html#Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
    name: GetViewdef
    href: Siesa.SDK.Frontend.Application.IViewdefManager.html#Siesa.SDK.Frontend.Application.IViewdefManager.GetViewdef(System.String,System.String)
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
